### ISSUE TITLE
Add a logical keyboard option similar to that in BeebEm

### ISSUE THREAD

**Issue by ZornsLemma** [stardot/b-em#78]
I use BBC emulators to play around with things like compilers and terminal emulation and I would really like to be able to put b-em into a mode where the keyboard on my PC "just works", e.g. if I press shift-8 I get "*" not "(". On BeebEm I can use the logical keyboard option, but I can't see anything similar in b-em. The key remapping dialog seems to be about mapping physical keys on the emulated machine to physical keys on my PC's keyboard, but that isn't enough here.

I'd potentially be interested in having a go at implementing this myself (although I'd be delighted if someone else did the work!), but I thought I'd raise this issue in case this functionality already exists and I'm missing it or there's some fundamental reason this is just not possible.

**Comment by SteveFosdick** [comment]
I can see a couple of complexities here:

1. Does allegro give the ASCII/Unicode code for the key pressed according to the layout of the current PC keyboard.  I think it does, but a different even from the one we currently use to give an Allegro internal key code.

2. We then need to emulate presses and releases of the shift key as necessary as there may be characters that can be typed on the PC keyboard without shift down that need shift on a BBC micro and vice versa.

Apart from looking at how BeebEm does it it may also be worth checking out B-Em's keyboard.c commit 2cfd299e4e334b6058d16ebf9b14384c145af68f.  This introduces a paste from clipboard feature that did almost exactly this, i.e. it took ASCII codes from the text on the clipboard, translated to a BBC key and accompanying shift state, and then simulated those key presses.  That commit can be accessed from back on the master branch though it isn't present in the current HEAD because the clipboard paste now works another way which is much faster.

Another possibility is to use the current mechanism for the paste from clipboard - essentially this hooks (via the 6502.c module) the vector to remove a value from a buffer and, if that buffer is the keyboard and there is a clipboard string, returns a character from there rather than the real keyboard buffer.  That works well for clipboard paste as one is typically pasting into BASIC or some other application that reads keystrokes via the OS - it wouldn't work so well with games as it is not emulating the keystrokes at a hardware level.

**Comment by ZornsLemma** [comment]
Thanks very much for those suggestions, they were very helpful. I've had a crack at implementing this - I re-used the current paste from clipboard mechanism as the path of least resistance - and it actually seems to work pretty well, though I've only given it a fairly brief test so far. You can see the code here: https://github.com/ZornsLemma/b-em/tree/logical-keyboard

The basic idea is that we now process ALLEGRO_EVENT_KEY_CHAR events as well. We have an alternate version of the allegro2bbc table for logical keyboard mode which returns the do-nothing code 0xaa for most "normal" keys; this makes the key up/down handling ignore them so we don't get duplicate keypresses. ALLEGRO_EVENT_KEY_CHAR events generate a fake keypress via the os_paste_start() function only for keys which the alternate allegro2bbc table maps to the do-nothing code. This way things like ESCAPE and shift+function key continue to work properly.

In logical keyboard mode the F1 key on the PC keyboard maps to F1 on the BBC keyboard; F10 is used for BBC key F0.

I did flirt with forcing upper case in logical keyboard mode if the emulated machine's caps lock setting was on, but that seemed to just make things even more confusing so I decided it was better not to.

I've only tested this on Linux but I'd hope the changes apply equally to all platforms.

If you have a few minutes to review the code and let me know what you think I'd appreciate any feedback you have.

Cheers.

Steve

**Comment by SteveFosdick** [comment]
I hadn't though of using the current os_paste code for this - that's a clever idea as long as logical mode doesn't need to work with thing that access they hardware directly and it probably doesn't as games tend to use keys that are in a convenient physical position rather than worry about the keycaps.

Everything you've done looks very sensible and worked well when I tried it (on Linux).  There is nothing there that is obviously platform specific - Allegro should be handling that for the host keyboard.  Not now, but when I have more time I can try out a windows build just to be sure.

**Comment by SteveFosdick** [comment]
I started thinking about the small possibility that someone types a logically mapped key while clipboard paste is in progress.  Checking again what you've done it seems the behaviour is well defined in that it will abort the clipboard paste and the OS will read the typed character next.

In the process I did find one minor thing.  The clipboard string which is being fed to os_paste_start from the GUI module comes from the Allegro library so it will have been allocated with al_malloc and should really be freed with al_free.  The 6502 module isn't consistent about this as os_paste_remv uses al_free and os_paste_start uses free.  At the moment I don't think it makes any difference but if, in future, someone was to substitute a different implementation behind Allegro's memory allocator it would so we should probably use al_malloc and al_free consistently.

**Comment by ZornsLemma** [comment]
Cheers, I'll take a look at making those tweaks; I also have another idea for a small change which might improve the handling of Caps Lock so I want to try that out too.

**Comment by ZornsLemma** [comment]
Right, I've made the al_free() change on the logical-keyboard branch I gave the link to above. I've given it a quick test and it seems to work.

I've also created a new branch logical-keyboard-2 (https://github.com/ZornsLemma/b-em/tree/logical-keyboard-2) off the logical-keyboard branch. It includes the al_free() change but also switches to passing the A-Z keys through the normal physical keyboard code path, just as it passes things like ESCAPE and SHIFT.

I think this is better/less confusing because whether you get a capital or lower case A when you press the 'A' key on the keyboard no longer changes when you toggle between physical and logical keyboard mode. The Caps Lock key still works as normal.

(I don't know if it's Linux only, but I find it slightly confusing that toggling the Caps Lock when the emulator has focus *also* affects the host. But then again I'd probably find it slightly confusing under other circumstances - e.g. I don't realise the emulator has focus and want to change the host's Caps Lock state - if it didn't. I haven't changed this behaviour, I'm just making a note about it here to give some context.)

**Comment by SteveFosdick** [comment]
Thanks for fixing the al_free bug.  It was my fault but if I fixed it in master after you had forked it and then you were to submit a pull request we'd get a conflict.

The new way of handling letter keys seems to work well.

The caps lock state is an interesting issue.  On Linux at least, the default seems to be that the caps lock state for the host applies to the whole desktop rather an individual window.  When an emulated machine maintains its own caps lock state that leads to the odd behaviour.  It might be possible to fix that by trapping focus/blur events, remembering the host caps lock state when the window is focused, setting it the guest caps lock state while focused and then restoring the host caps lock state at the end.  I know this can be done under X but I am not so sure about Wayland or Windows so a bit more investigation needed there, I think.  It also supposes we can keep a record of the guest caps lock state and not have it drift from what the guest OS thinks, unless we use the BBC MOS's internal variable and how it doesn't move around from one version of the OS to another.

**Comment by ZornsLemma** [comment]
You're welcome, I hope I did it right.

The caps lock thing sounds like it has the potential to be a huge can of worms. I don't have any answers and I'm not sure it is really a big deal, I just thought it would be helpful to make the observation as it was related to my change. The one possible suggestion I do have is that we could use the state of the emulated machine's caps lock LED to determine if it thinks caps lock is on or off, though given in reality no one is ever going to run a non-Acorn OS on the machine and so we can peek into the OS workspace that's probably a better solution anyway.

It might also be nice (as a related issue) if there was some option to show the LEDs of the emulated machine in the emulator window; unless I'm missing this it isn't currently possible to see them.

**Comment by ZornsLemma** [comment]
I've just pushed another commit to the logical-keyboard-2 branch which also passes END (the emulated machine's COPY key) through the normal physical keyboard code even in logical keyboard mode; I hadn't tried this before.

However, I've found another problem. It's not a total killer but it's annoying. The logical keyboard mode goes wrong if you try to type ahead; I suspect (but haven't yet investigated) this is because each call to os_paste_start() cancels any pending paste, and this just hasn't normally been a problem because the emulated machine can keep up with human-speed typing when it's not doing anything else. You can see this by putting a writeable disc in the emulated drive, doing "*SAVE Q 3000 4000" and while that's saving, type "*DUMP Q". When the prompt returns after the save, you'll see " DUMPQ" instead of "*DUMP Q". I'll have a poke to see if I can fix this...

**Comment by ZornsLemma** [comment]
OK, I've had a bit of a play with this and I think this approach might be falling apart. :-(

I experimentally created an os_paste_append() which adds to the end of the to-be-pasted string instead of replacing it, and used that in key_char() instead of os_paste_start(). That helped a bit, but it's still not right. If you type:

`*DUMP "Q"`

during the *SAVE, the output on the emulated machine is:

`* ""DUMPQ`

I think I see why this is happening - I think the keys which go via the physical keyboard code get put into the keyboard buffer by the Acorn OS acting on the key pressed interrupts but the keys which are going via os_paste*() effectively jump to the front of the keyboard buffer.

There may be an easy fix but I'm going to sleep on it as I don't currently see it. :-) Any suggestions welcome, of course...

**Comment by SteveFosdick** [comment]
That makes sense because os_paste_start isn't adding characters to a buffer - we are temporarily replacing the real keyboard buffer with a fixed string.  I choose that was for pasting via clipboard as the alternative of inserting into the real keyboard buffer would need some complexity around avoiding overflowing it.

I don't think that means re-using os_paste is flawed, we just need a slighly more compex function to deal with the typed characters.  Something like this (in 6502.c):
```
void os_paste_addc(int ch)
{
    static const char memerr[] = "6502: out of memory adding character to OS paste, character discarded");

    if (clip_paste_str) {
        int len = strlen(clip_paste_ptr);
        int pos = clip_paste_ptr - clip_paste_str;
        char *new_str = al_realloc(clip_paste_ptr, len+2);
        if (new_str) {
            clip_paste_str = new_str;
            clip_paste_ptr = new_str + pos;
            new_str[len] = ch;
            new_str[len+1] = 0;
        }
        else
            log_warn(memerr);
    }
    else {
        char *new_str = al_malloc(2);
        if (new_str) {
            new_str[0] = ch;
            new_str[1] = 0;
            clip_paste_str = new_str;
            clip_paste_ptr = new_str;
        }
        else
            log_warn(memerr);
    }
}
```

**Comment by ZornsLemma** [comment]
Thanks, that is remarkably similar in intent (though better; for one thing, it checks for null returns from al_realloc/al_malloc :-) ) to my os_paste_append(). I couldn't push that last night as my internet connection went down. FWIW I have now switched to using a tweaked version of your os_paste_addc() and you can see the code on the logical-keyboard-3 branch in my repo.

However, while your code is better, it is functionally equivalent to mine and so doesn't fix the issue where e.g.:

`*DUMP "Q"`

gets turned into:

`* ""DUMPQ`

if you type it while the emulated machine is busy (e.g. doing a *SAVE Q 3000 5000).

I think the problem here is that the *, space and double-quote characters get passed to os_paste_addc() which puts them into the emulator's own paste buffer, while D, U, M, P and Q get passed via keyboard interrupt to the OS, which puts them into the OS's keyboard buffer. When the OS tries to read from the keyboard buffer, it gets everything from the emulator's own paste buffer before anything from the OS's keyboard buffer, which means *, space and the double-quote characters effectively jump to the front of the queue.

I'm starting to think it may be necessary to resurrect some of that old code you referred me to up above and generate fake keyboard events for all keys in logical keyboard mode instead of (ab)using the paste code, in order to avoid this sequencing issue.

**Comment by SteveFosdick** [comment]
Ok, so the issue is that the order in which the characters are read is not the order in which they were typed.  I can see that in your comment immediately before mine.  I am not sure if I just missed that or hadn't read that comment this morning.

Another possibility is to send all input via the OS paste route though obviously that does limit the use of logical mode to things that read the KB via the OS.

The issue with the simulated keystrokes way of pasting was that it was slow.  The way the OS notes the key has been pressed in the ISR but delays adding it to the keyboard buffer until a timer driven routine that follows limits the rate of typing to the timer interval.  That wasn't too bad for a 10 line BASIC program - it was even cool to watch - but tedious for 500 lines.

The speed should not be an issue here as the speed should be limited by the person typing.

**Comment by ZornsLemma** [comment]
Thanks, I think I'd definitely prefer the simulated keystrokes approach if I can make it work - the reason I originally started to pass "most" keys through the physical keyboard routine even in logical keyboard mode was that pasting doesn't really work (because it doesn't need to for actual pasting) for things like cursor and function keys. You're right that the speed shouldn't be an issue in this case, unlike pasting.

I'll see if I can get some time to take a look at it later this week; watch this space for questions. :-)

**Comment by SteveFosdick** [comment]
In an idle moment I thought I would remind myself of the keyboard paste code and I discovered the modules concerned have a bunch of other changes since that might making it hard to see the wood for the trees.

So, I have created a branch with the keyboard-based paste back working at https://github.com/stardot/b-em/tree/sf/keypaste

Hopefully that may be easier to use a reference than just winding back the clock to the commit I mentioned earlier.

**Comment by ZornsLemma** [comment]
Thanks for that, much appreciated. I have been mulling this change over but haven't yet got round to implementing it, as I'm hoping to have a brainwave. What worries me about reusing the keyboard-based paste code is whether it's going to cope with things that don't happen in an actual paste-from-clipboard, like the cursor keys, the function keys, etc. I haven't tried this yet so maybe it's fine; I will have a play with your new branch and see how it goes.

**Comment by ZornsLemma** [comment]
After a certain amount of hair-pulling I've re-implemented logical keyboard handling using a modified version of the keyboard-based paste code from your sf/keypaste branch. You can see this on my branch here: https://github.com/ZornsLemma/b-em/tree/logical-keyboard-5

The basic approach is that we queue up *keycodes* in the to-be-pasted string, not characters; SHIFT/CTRL up/down events are represented by pseudo-keycodes in that string. This means that we can capture SHIFT/CTRL state as the user types and we receive KEY_CHAR events.

I hope this approach doesn't seem overly complicated. What I had in mind was that I also wanted the SHIFT and CTRL keys to be testable from within the emulated machine in logical keyboard mode. Assuming your PC keyboard is like mine and has colon on SHIFT+semicolon and plus as SHIFT+equals, if you do "REPEAT:PRINT INKEY-1,INKEY-2:UNTIL FALSE" at the BASIC prompt, you can see that:
- if you hold SHIFT or CTRL the relevant INKEY-n returns -1, and goes back to 0 when the key is released
- if you press "=" without holding down SHIFT, the INKEY-1 output briefly blips to -1 as the logical keyboard code depresses the emulated machine's SHIFT key ("=" being a shifted key on the BBC keyboard), then goes back to 0
- if you hold down SHIFT and press ";", thereby typing a colon (which is an unshifted key on the BBC keyboard), the stream of -1s from SHIFT being held down will briefly blip to 0 while the colon is being typed before returning to -1.

I obviously haven't had much time to test this in normal use yet, but it does seem to work fairly well in the tests I've done so far. The main flaw I'm aware of is that auto-repeat is handled by the host machine, not the emulated machine, because the paste-typing never holds down a key for long enough to auto-repeat; instead what happens is we receive repeated KEY_CHAR events and process each separately. This works pretty well, but there is a kind of lag; in physical keyboard mode the instant you release the auto-repeating key the emulated machine stops receiving it, in logical keyboard mode it keeps appearing for a while. I am not sure if there's any way round this.

While I've hacked it up quite a bit, I don't think I could have done this without your code as a starting point - I suspect the knowledge embedded in your code of how long it's necessary to delay after pressing a key is the result of either extensive trial and error or making the effort to understand how the Acorn OS handles the keyboard in quite some detail. Even with your code to start from, I had all my emulated keypresses disappearing at one point, then later I tried to get rid of the KP_CHAR state and fold it into KP_NEXT, only to find it mostly worked but would occasionally lose keys if I typed too fast. So thanks a lot for that!

Please let me have any comments you might have on the code, it's quite possible it can be simplified and/or improved, or (fingers crossed) may have bugs in I've managed to overlook.

**Comment by SteveFosdick** [comment]
I will see if I can get round to trying this later today or at the weekend.

I didn't go through the OS disassembly myself but I did know that key processing was split between the initial interrupt from the KB and the subsequent 10ms timer interrupt so there would need to be some delay.  Then I experimented to see how long.

**Comment by ZornsLemma** [comment]
FWIW I am playing around with an alternate version which handles key auto-repeat better. (In physical keyboard mode, I can type a long line of BASIC then hold the left/right cursor keys and release the key pretty much when the cursor hits any character I choose; in logical keyboard mode there's an overshoot of a few characters. This isn't the end of the world, but it is a bit annoying and feels wrong.)

Right now the alternate version is a mostly broken pile of hacks but I can't help feeling there's potential there. It's still quite similar to the logical-keyboard-5 branch so if you have the time and inclination to review that I doubt it will be completely wasted time, but you might prefer to wait until I either have the new code ready for you to look at or give up on it and declare logical-keyboard-5 the best I can manage. It's up to you, of course, I just thought I'd let you know what I'm up to in this area...

**Comment by ZornsLemma** [comment]
I managed to get the alternate version working and I must admit I'm quite pleased with the result. You can see it here: https://github.com/ZornsLemma/b-em/tree/logical-keyboard-8

The basic idea is that we now push key up/down 'events' into the paste buffer, not characters or keycodes. We generate those up/down events in response to Allegro KEY_UP/KEY_CHAR events respectively. key_paste_poll() is responsible for feeding those events into the emulated machine; we still need this instead of just hooking KEY_UP/KEY_CHAR directly to the emulated keyboard because we have to be careful to only "fake" SHIFT keypresses when it's not going to have any effect on other keys held down at the same time.

I think there is a tiny amount of lag compared to physical keyboard mode but it's nowhere near as noticeable as it was with the logical-keyboard-5 branch. If you hold down "A" until it starts auto-repeating and then let go of the key, the auto-repeat stops pretty much immediately, unlike logical-keyboard-5.

I've also done a little bit of tidying around resetting the keyboard when toggling between physical and logical keyboard modes and making sure the VDFS S-BREAK works; I haven't explicitly tested but I suspect these are small flaws in logical-keyboard-5 which we'd need to fix if we want to proceed from that code instead. Personally, I'd much rather go with this new version, of course.

Let me know if you have any questions or comments and I'll take a look; no rush, of course!

Cheers.

Steve

**Comment by SteveFosdick** [comment]
Ok, I finally got a chance to clone your branch and test it, and it seems to work well.  Looking at the code it does seem processing the shift/ctrl state is a now a bit more complicated than it was when pasting mostly ASCII characters from the clipboard.  I am still working through that bit.

**Comment by ZornsLemma** [comment]
Thanks for taking a look! If you have any questions about shift/ctrl once you've had a look just let me know. I think the key (no pun intended) thing is that because the user is also operating these keys, we need to be careful not to interfere with his/her typing when "faking" shift presses to type the desired character on the emulated machine. Some of my test cases while working on this code were things like:

- holding shift down and rapidly typing "as:" over and over again - as far as the user's concerned shift is always down and it's that simple, but we need to temporarily remove shift while typing ":" as that's unshifted on the BBC - if you get the implementation wrong you will see things like capital "A" or "S" appearing and maybe even the odd "*". [I'm assuming "shift caps" mode here, either by *CONFIGURE setting on the Master or by pressing SHIFT+CAPS LOCK on a BBC B. Otherwise you can't tell the difference between shifted and unshifted a/s, of course.]

- holding down "a" and intermittently pressing and releasing shift

- holding down ";" (assuming your keyboard has SHIFT+";"=":" like mine) and intermittently pressing and releasing shift

The implementation strategy is that we only ever have one non-SHIFT/CTRL key pressed on the emulated machine's keyboard at any one time. This is all we need - remember Allegro/the emulator is queuing up key events so this doesn't mean the physical user can only press one key at a time - and that way we can ensure we only futz with the SHIFT/CTRL state when no ordinary key is down.

**Comment by SteveFosdick** [comment]
The holding down ';' while pressing and releasing shift does not seem to be quite right.  In physical keyboard mode, if I hold down that key so it repeats and then press and release shift it continues to repeat but swaps between ; and + without interruption.

In logical mode each time I press or release the shift key the auto-repeat pauses and re-starts.

There is also a tiny memory leak in key_reset which is setting key_paste_str to 0 without checking if it currently points to anything.

**Comment by SteveFosdick** [comment]
On the repeat behaviour, I think where you do:
```
        if (!event->keyboard.repeat ||
            (event->keyboard.unichar != last_unichar[event->keyboard.keycode])) {
            last_unichar[event->keyboard.keycode] = event->keyboard.unichar;
            set_key_logical(event->keyboard.keycode, event->keyboard.unichar, 1);
        }
```
and check whether the unicode character has changed, I think you need to map it to a keycode first and then check if it the same BBC key.  That's an interesting trick, BTW, of learning the character to keycode mapping as you go along, so you can match keyup events to key char events.

**Comment by ZornsLemma** [comment]
I think the behaviour of ';' you describe is correct; as far the emulated machine is concerned, we are letting go of the ';' key and then pressing the ':' key, so the Acorn OS auto-repeat delay-before-repeating kicks in again. In physical keyboard mode the same emulated machine physical key is held down continuously. In physical keyboard mode pressing the ";" and ":" keys (host keys ";" and "'") alternately has a similar effect to toggling SHIFT with the ";" key held down in logical keyboard mode. It would be nice if this didn't happen, but short of playing around with the OS variables I don't think it can be helped. I hope I haven't missed your point here. (What I've been at pains to prevent in the implementation is any stray SHIFT events causing odd characters like "*" or "+" appearing when you do this kind of thing, since that is something we can prevent just by taking care which emulated keys we have down at any one time.)

Good spot on the memory leak, I've pushed a fix for this.

**Comment by ZornsLemma** [comment]
Incidentally I did wonder if it might be better (or at least more elegant) to rejig the key_paste_str stuff so we keep a buffer allocated all the time and just grow it if necessary, rather than allocating and freeing multiple times on every keypress. I doubt it has a noticeable performance impact but it feels a bit wrong. What do you think? I'm happy to give this a try, I just haven't done it yet, and maybe the current approach is slightly simpler and we should prefer that when there's no real problem with it in practice. (It obviously made a lot of sense to do the allocations when this code was being used for clipboard pastes, but it's mutated a bit since then!)

**Comment by SteveFosdick** [comment]
Indeed I had overlooked that the key as seen by the BBC micro was changing, hence the start to the auto repeat.

It isn't performance critical but yes, I think it makes sense to leave the buffer allocated between key presses.  On a 64 bit machine malloc will probably round up all allocations to a multiple of 8 bytes anyway so may as well start with that and then it probably won't need many calls to realloc.

Otherwise it is looking good.

**Comment by ZornsLemma** [comment]
Cheers, I'll take a look at reworking the allocation over the next day or two.

**Comment by ZornsLemma** [comment]
So I've had a look at reworking the allocation, and you can see the results so far here on the new logical-keyboard-9 branch: https://github.com/ZornsLemma/b-em/tree/logical-keyboard-9

Fortunately/unfortunately doing this made me think about a few things and the change isn't therefore just a tweak to how the dynamic allocation is handled.

I realised that the previous version of the code could effectively allow the paste buffer to grow arbitrarily large - as long as the user keeps hitting keys (they could just be mashing the keyboard) and keeps a fraction ahead of the timer-limited key_paste_poll() state machine, it would never free the key_paste_str buffer.

So I reworked it to use a fixed-size array (which also avoids the minor but disquieting possibility of the keyboard stopping working due to a realloc() failure) and shuffle the buffer down occasionally to free up the already-processed initial part before key_paste_ptr. This worked and that code is still present in the logical-keyboard-9 branch.

I also realised that because the user can stay ahead of key_paste_poll(), we effectively have a second level of type-ahead above that provided by the emulated machine's own OS keyboard buffer. I don't think this is a good thing; the OS keyboard buffer gets cleared in relevant circumstances (e.g. pressing Escape) whereas the buffer provided by the logical keyboard code is immune to such things. My solution to this is to stop allowing key down events into key_paste_str once it gets over a certain unprocessed data size - a size chosen with a view to avoiding more than a few centiseconds of extra typeahead. We let key up events in so we don't end up with emulated machine keys sticking down when this threshold is exceeded.

The code on the logical-keyboard-9 branch works as described above and it seems to work fairly well to me. I hope I'm not ridiculously over-complicating things here, but maybe you'll be able to point out something obvious I've managed to overlook. I do think it's good to avoid having a significant amount of type-ahead created by the logical keyboard code though.

The old code also had the possibility that e.g. a VKEY_UP would get into the buffer and it would then not be allowed to grow any more due to realloc() returning null and the byte expected to follow VKEY_UP doesn't make it into the buffer. key_paste_poll() could then access off the end of the string because it assumes VKEY_UP/VKEY_DOWN were guaranteed to have a byte after them (not unreasonable, in itself). The rework makes inserting these double-byte sequences atomic to avoid this.

**Comment by ZornsLemma** [comment]
Thanks for doing the work to rebase this to latest master! I've given it a quick test and it seems to work fine. I've also reviewed the code; it does seem complex but I think the discussion above shows why it's complex. It would be really great to get this onto master, I do miss this change (primarily because I keep making mistakes typing "&" into the emulated BBC) when I don't have it.

I also did a diff of your sf/logicalkey branch with my logical-keyboard-9 branch and checked all the diffs looked unrelated to the keyboard. (It's also obvious how much work has been going into b-em in other areas from doing this. It's quite impressive!)

I don't think it really matters too much about losing the commit history in git; it will be there on my branch anyway, and the discussion above is probably more illuminating than the code if someone is trying to understand why it's as fiddly as it is (although I can't help suspecting some genius is going to come along and replace all this with a dozen lines of code at some point).

In the process of reviewing it I did find a probable bug (which I originally perpetrated) - memcpy() in key_paste_add_vkey() is copying overlapping regions and so we should be using memmove(). What do you think?

**Comment by SteveFosdick** [comment]
I have implemented the memmove fix.  I have also merged the current master into the sf/logicalkey branch so that picks up the LEDs, the optimised Music 5000, debugger symbols etc. and I have also re-implemented my fix for the pre-AT numeric keypad in a way that does not rely on a patched allegro.  What it does is delay processing a key from the numeric keypad until the key char event when it gets the unicode character.  If that is a digit it performs a key down on the Master numeric keypad key and if it is not a digit it does the key down on the equivalent key for cursor movement. 

I don't think this fix is working in logical mode, though.  It might be as simple as changing the order of the tests in the key_char function - that would mean in keypad mode, when the key pressed is on the keypad, the mapping is always physical but that may not be a problem.  The alternative is to work out a similar fix to logical mode.

I was talking in the comments of the redraw when paused bug about how this Master keypad is mapped as we have PageDown performing both an emulator pause and the keypad '.'.  I was thinking we should move from a two stage mapping where an Allegro key code is first mapped to another Allegro key code via the user-defined mapping and then mapped to the BBC key.  Looking more closely it may be the way it is because that allows the emulator control keys to be re-mapped too, i.e. that's why there is a separate call to the keyboard module to map the key before a switch statement in main.c that does some emulator control stuff before calling key_down.  I don't think there is a UI to do that mapping, though.

Any thoughts welcome on this.  And testing, of course.  I am hoping by merging master into this branch it should be a good one to try for day to day use.

**Comment by ZornsLemma** [comment]
I've just built the latest code on the sf/logicalkey branch and will make that my day-to-day b-em and see how I get on. So far it looks really good, and I can't wait to get accustomed to having logical keyboard mode readily available. (I have recently been writing BBC BASIC code in vim on my PC and I've noticed that I start typing as if I'm on b-em in physical keyboard mode and so nothing comes out right. :-) )

I don't think it's a big deal and I don't know if it ever worked, but for what it's worth: if I turn Num Lock off on my (Linux) host, in logical keyboard mode the cursor keys on the numeric pad don't have any effect, rather than acting as the BBC cursor keys as I might naively have expected. (In physical keyboard mode the host Num Lock status makes no difference, which seems sensible.)

I agree there's probably scope for cleaning things up here in general but I don't have any amazing insights. One thing I would suggest - off the top of my head - is that maybe we should use internal non-Allegro keycodes for things like "pause the emulator" and "enter fullscreen", and have key_map map physical Allegro keycodes to those internal codes, rather than have it map one physical Allegro keycode to another. Maybe we could also make the corresponding menus submit those internal codes as if typed on the keyboard, rather than act directly, so that things are always consistent whether you use a keyboard shortcut or the GUI to do something. (Ignoring some of the in-progress pause rework, for example, at the moment pausing via Page Down and pausing via the menus don't interact with each other very well.) Maybe this doesn't make much sense, I am just throwing the idea out.

**Comment by SteveFosdick** [comment]
I re-tested this and it looks like I didn't get it quite right.  From only working in physical mode I had made it so the keypad only worked in logical mode (by piggy-backing on the logical mode code).

So I have pushed another commit that I believe resolves this.  It reorganises some of the tests (in key_char) in order to avoid duplicating some of the code between a delayed keypad keypress in keypad mode and any key press in logical mode.  It now seems to do something sensible in each of these situations:
```
Logical?  Keypad?  Numlock?  Result
========  =======  ========  =====
Physical  Off      Off       Numbers
Physical  Off      On        Numbers
Physical  On       Off       Cursor keys
Physical  On       On        Numbers
Logical   Off      Off       does nothing
Logical   Off      On        Numbers
Logical   On       Off       Cursor keys
Logical   On       On        Numbers
```

**Comment by ZornsLemma** [comment]
Sorry for the delaying in getting back to you on this...

I've just built the latest code on the sf/logicalkey branch and given it a quick test and I believe all the eight cases you mention are working fine, thanks. (I don't have a patched Allegro; I am not sure if this should matter or not.)

Although I use the numeric keypad very little on any system, I'd probably want keypad mode on even though I have a modern keyboard. (I did write a paragraph suggesting everyone would want this on and there's no need for it to be an option, but I changed my mind in the course of writing it...) If we hadn't had this discussion I'd have probably dismissed it as irrelevant with the name "PC/XT Keypad Mode" I wonder if it should be renamed to something like "respect Num Lock"? I suppose that's not a good name anyway, because in logical keyboard mode we "respect" Num Lock to some extent whatever the setting of this option.

However, I have to say that the least logical bit of behaviour to me - at least right now, I might give a different answer if you asked me tomorrow :-) - in the above table is the row with the "does nothing" behaviour. In logical keyboard mode the Keypad=On behaviour just seems so much more correct that I find the "does nothing" strange. Harmless, given it's always possible to set Keypad=On, but strange.

**Comment by SteveFosdick** [comment]
It's good that you don't have the patched Allegro - this version was intended to work without that.

The reason for making this keypad mode optional in the first place was because of a dependency on the Allegro patch.  Without the patch, numlock would always appear to be off so the keypad would always duplicate the cursor keys and never send numbers so it would never behave like the real keypad on a Master.  That issue is gone now I have re-worked it to use key char events for the numeric keypad keys.

So on the numeric keypad in general, prior to getting the Model F, I always found it silly that numlock defaulted to off.  My reasoning was that with keys dedicated to up, down, left, right, home, end, page up, page down, insert and delete, why would I ever want to use the numeric keypad for these functions?  Why not treat that keypad as if numlock were permanently on?  But, of course, it defaulted to off on the original PC, XT and AT so that remains the default.

Then I would have to go digging for settings.  If I got the BIOS to turn numlock on the Linux kernel promptly turned it off again.  I could then get Linux consoles to default it to on and X or Wayland then turned it off again etc. 

But back to how this should behave in B-Em, in physical keyboard mode we ignore the state of caps lock on the host and let the guest OS implement its own caps lock/shift lock model.  The BBC Master OS doesn't have the concept of numlock and cursor keys have been on the BBC micro from day one so the dual use of the numeric keypad has never applied to the Master itself.  So on a PC with the enhanced keyboard (PS/2 and later) it makes sense to also ignore the state of numlock and always generate the master keypad matrix codes for those keys.  That doesn't work on the pre-enhanced keyboard, though, i.e. PC, XT or AT as these don't have the cursor keys so the numeric keypad must perform those functions and numlock is the obvious way to determine what the numeric keypad should do.  SO that is why it is currently an option - so if you have the enhanced keyboard you don't have to engage numlock for the master to see the PC numeric keypad as its own numeric keypad.

As for the case of "does nothing" perhaps that should generate numbers?

**Comment by SteveFosdick** [comment]
Getting the combination where the keypad does nothing to generate numbers proved not to be straightforward because those keys are mapped to 0xaa to use the unichar and this is zero if numlock is off.  So, instead, in logical mode I treat XT Keypad (respect numlock) mode as being always on so in logical mode the keypad will always generate cursor keys with numlock off and numbers with numlock on.  I have pushed this commit to the sf/logicalkey branch.

**Comment by SteveFosdick** [comment]
I have come up with a re-work of the keymapping.  Rather than repeat the details here, they are in the commit message.  As it's a bigger change I have put this on a new branch: https://github.com/stardot/b-em/tree/sf/newkeymap.

**Comment by ZornsLemma** [comment]
I think we are mostly in agreement re Num Lock - personally I always have it on, except when I've accidentally turned it off, and I half wish there was a way to have it just be always on and disable the Num Lock key. However, given it does exist and it does default to off etc etc, it seems logical (no pun intended) to me that in "logical keyboard" mode it should have the same effect on the emulated machine as it does on the host, warts and all - that for me is practically the definition of "logical keyboard" mode; it's as if the PC keyboard is hooked up to a BBC and somehow magically made to work. I agree it makes sense for Num Lock not to have an effect in physical keyboard mode, and the Caps Lock analogy is very well made.

I have had a look over the commit on the newkeymap branch. I don't claim to be all that familiar with the old way of doing things, but the new commit seems fairly clean. I will switch to using it as my working version of b-em and see how I get on. I did notice there is a persistent typo though - there is a variable called "bbcmaxtrix" which I would have expected to be "bbcmatrix". Probably not the most helpful code review comment ever!

Cheers.

Steve

**Comment by ZornsLemma** [comment]
OK, I just switched to the new branch - I hadn't done that when I wrote the previous comment.

Not a huge deal at this point, but maybe worth noting - I had to move my old b-em.cfg file aside in order to get the keyboard to work at all. I didn't spend a lot of time investigating this, but if you can reproduce it (and you didn't already know about it) it may be worth remembering to add some kind of migration support when/if this gets pushed to master.

Also, although the branch seems to include the logical keyboard mode and keypad mode, the GUI code omits them so you can't see them or control them in the menus (maybe you can edit b-em.cfg directly, I haven't tried this yet).

**Comment by SteveFosdick** [comment]
I was surprised by the disappearance of the GUI but it turns out that was a git mistake - accidentally based the new branch on master and not sf/logicalkey.  I have pushed a new branch: https://github.com/stardot/b-em/tree/sf/newkeymap2 which resolves this.

**Comment by ZornsLemma** [comment]
Thanks, that's fixed that. I'll use this and see how I get on.

One small problem so far (which I've made no effort to debug myself yet) - in logical keyboard mode, the "./Del" key on the numeric pad acts as "Del" whether Num Lock is on or off. I'd expect it to act as "." if Num Lock is on.

**Comment by SteveFosdick** [comment]
Ok, I have pushed a commit that fixes that.  It does feel like a little bit of a bodge, though, because it is mapping the keypad key to the normal full-stop key.  I'll run some tests later to see if I can find any further problems with it.  One advantage of this fix is that it also applies to XT keypad mode with physical mapping.

The other possible fix is to have a code in the logical keymap table that means "if there is a unicode char (not zero) then translate via that, otherwise refer to the physical map for this keycode".

**Comment by SteveFosdick** [comment]
Another possibility is to change the logical keymap for the KP_DEL key to '.' and then have map_keypad_intern do the opposite mapping, i.e. map KP_DEL to regular DEL if the unicode character is not '.'.

**Comment by ZornsLemma** [comment]
I can confirm the fix works for me, so thanks for that - I will keep using this branch and let you know if I find any other problems.

I have to confess that while I do sort of understand the different fixes you've proposed, this kind of mapping stuff makes my head spin a bit. I see what you mean about the bodge, but in some ways that is probably necessary - I actually tested this using BBC B emulation (it wasn't obvious because I had a 6502 second processor as well) and of course the logical keypad code needs to be able to generate characters accepted by the emulated model B from the numeric keypad even though the real hardware doesn't have one.

**Comment by SteveFosdick** [comment]
I think is is probably working well enough now.  If not we can always re-open.

**Comment by SteveFosdick** [comment]
Note a new bug has been raised in connection with this: https://github.com/stardot/b-em/issues/226
